Initial README revision
veraison/services pull request #12
Opened 2022-08-17 17:59 UTC by yogeshbdeshpande

2022-08-17 19:14 UTC, setrofim requested changes
On a general note --  I'm confused by the capitalisation of terms. It seems inconsistent. E.g. "Attestation Evidences claims" but "Attestation Verification Results"  (both on line 15). Also "Attestation Result" is capitalised, but "attestation format" is not. Am I missing an underlying pattern?

2022-08-17 19:14 UTC, setrofim commented on README.md
> +Veraison Trusted Services(VTS) provides core services to the Verification and Provisioning front end services. On Provisioning path, it receives Endorsements and Trust Anchors, from [Provisioning](#P
```suggestion
Veraison Trusted Services (VTS) backend provides core services to the Verification and Provisioning frontends. On the Provisioning path, it receives Endorsements and Trust Anchors, from the [Provisioning](#Provisioning) frontend, invokes attestation format (e.g. PSA) specific logic (a "scheme") to generate Endorsements and Trust Anchors, and saves them in the corresponding stores. On the Verification path, it invokes attestation format specific logic (a "scheme") to parse attestation token and extract evidence claims. From these claims, it constructs a logical index/key to fetch the trust anchors required to validate the token, and the associated Endorsements (`golden values`) used to appraise the evidence claims. Upon evaluation, it populates the Attestation Result and communicates it to the [Verification](#Verifcation) frontend.
```

2022-08-17 19:14 UTC, setrofim commented on README.md
> +The key-values store is Veraison Storage Layer. It is used to store both Endorsements and Trust Anchors, as key and values.
```suggestion
The key-values store is the Veraison Storage Layer. It is used to store both Endorsements and Trust Anchors.
```

2022-08-18 10:00 UTC, yogeshbdeshpande commented
> On a general note -- I'm confused by the capitalisation of terms. It seems inconsistent. E.g. "Attestation Evidences claims" but "Attestation Verification Results" (both on line 15). Also "Attestation Result" is capitalised, but "attestation format" is not. Am I missing an underlying pattern?

No pattern, key words used are capitalized. for consistency, I have changed Attestation Format. Will check again for consistency.

2022-08-18 10:04 UTC, setrofim approved these changes

2022-08-18 10:26 UTC, merged